version: "3.9"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: "mssql"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=e7dff8dc-5d35-4483-9be6-38f47da16b95
